/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;


import DAO.CadastroDAO;
import Model.CadastroPaciente;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author Victo
 */
public final class Cadastro_Paciente extends javax.swing.JFrame {
   
    /**
     * Creates new form Cadastro_Paciente
     *java.sql.SQLException
     * @throws java.sql.SQLException
     */
    public Cadastro_Paciente() throws SQLException {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tabelaPesquisar.getModel();
        tabelaPesquisar.setRowSorter(new TableRowSorter(modelo));

        readJTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPasswordField1 = new javax.swing.JPasswordField();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        menuBar3 = new java.awt.MenuBar();
        menu5 = new java.awt.Menu();
        menu6 = new java.awt.Menu();
        popupMenu1 = new java.awt.PopupMenu();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        campoAlterar = new javax.swing.JButton();
        campoNome = new javax.swing.JTextField();
        campoIdade = new javax.swing.JTextField();
        campoEndereco = new javax.swing.JTextField();
        campoTipo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        campoDeletar = new javax.swing.JButton();
        campoGravar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPesquisar = new javax.swing.JTable();
        botaoPesquisar = new javax.swing.JButton();
        campoCPF = new javax.swing.JFormattedTextField();
        campoTelefone = new javax.swing.JFormattedTextField();
        bntSair = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        campoSituacao = new javax.swing.JTextField();
        campodeletar = new javax.swing.JButton();

        jTextField7.setText("jTextField7");

        jLabel2.setText("jLabel2");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPasswordField1.setText("jPasswordField1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        menu5.setLabel("File");
        menuBar3.add(menu5);

        menu6.setLabel("Edit");
        menuBar3.add(menu6);

        popupMenu1.setLabel("popupMenu1");

        jFormattedTextField1.setText("jFormattedTextField1");

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jLabel10.setText("jLabel10");

        campoAlterar.setText("Alterar Cadastro");
        campoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAlterarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("CADASTRO PACIENTE");

        jLabel3.setText("Nome:");

        jLabel4.setText("CPF:");

        jLabel5.setText("Preencha os dados abaixo para cadastro do paciente:");

        jLabel6.setText("Idade:");

        jLabel7.setText("Endereço:");

        jLabel8.setText("Telefone:");

        jLabel11.setText("Comorbidade:");

        campoDeletar.setText("Limpar");
        campoDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDeletarActionPerformed(evt);
            }
        });

        campoGravar.setText("Salvar");
        campoGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoGravarActionPerformed(evt);
            }
        });

        tabelaPesquisar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "Idade", "Endereço", "Telefone", "Comorbidade", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaPesquisar);
        tabelaPesquisar.getAccessibleContext().setAccessibleParent(tabelaPesquisar);

        botaoPesquisar.setText("Pesquisar Paciente");
        botaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarActionPerformed(evt);
            }
        });

        try {
            campoCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            campoTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelefoneActionPerformed(evt);
            }
        });

        bntSair.setText("Sair");
        bntSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSairActionPerformed(evt);
            }
        });

        jLabel12.setText("Situação:");

        campodeletar.setText("Deletar Paciente");
        campodeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campodeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(bntSair, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(253, 253, 253)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(campoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(campoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(campoSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(142, 142, 142)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(campoDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(campoGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campodeletar)
                                    .addGap(18, 18, 18)))
                            .addComponent(botaoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntSair)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(1, 1, 1)
                .addComponent(jLabel9)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoDeletar)
                    .addComponent(campoGravar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botaoPesquisar)
                        .addComponent(campodeletar)))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel11, jLabel12, jLabel3, jLabel4, jLabel6, jLabel7, jLabel8});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    public void readJTable() throws SQLException {
        
        DefaultTableModel modelo = (DefaultTableModel) tabelaPesquisar.getModel();
        modelo.setNumRows(0);
        CadastroDAO pdao = new CadastroDAO();
        

        for (CadastroPaciente cadastros : pdao.listar()) {

            modelo.addRow(new Object[]{
                cadastros.getID(),
                cadastros.getNome(),
                cadastros.getCpf(),
                cadastros.getIdade(),
                cadastros.getEndereco(),
                cadastros.getTelefone(),
                cadastros.getComorbidade(),
                cadastros.getSituacao()
            });

        }

    }
    
    
    
    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    private void campoGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoGravarActionPerformed
        
        if(campoNome.getText().equals("")){
        
        JOptionPane.showMessageDialog(null, "Preencha o campo Nome!", "aviso", JOptionPane.WARNING_MESSAGE);
        return;
        }if(campoCPF.getText().equals("   .   .   -  ")){
        
        JOptionPane.showMessageDialog(null, "Preencha o campo CPF!", "aviso", JOptionPane.WARNING_MESSAGE);
        return;
        }if(campoIdade.getText().equals("")){
        
        JOptionPane.showMessageDialog(null, "Preencha o campo Idade!", "aviso", JOptionPane.WARNING_MESSAGE);
        return;
        }if(campoEndereco.getText().equals("")){
        
        JOptionPane.showMessageDialog(null, "Preencha o campo Endereco!", "aviso", JOptionPane.WARNING_MESSAGE);
        return;
        }if(campoTelefone.getText().equals("(  )     -    ")){
        
        JOptionPane.showMessageDialog(null, "Preencha o campo Telefone!", "aviso", JOptionPane.WARNING_MESSAGE);
        return;
        }if(campoTipo.getText().equals("")){
        
        JOptionPane.showMessageDialog(null, "Preencha o campo Comorbidade!", "aviso", JOptionPane.WARNING_MESSAGE);
        return;
        }if(campoSituacao.getText().equals("")){
        
        JOptionPane.showMessageDialog(null, "Preencha o campo Situacao!", "aviso", JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        try {
            // TODO add your handling code here:
            CadastroPaciente cadastros = new CadastroPaciente();
            
            CadastroDAO cadastroDAO = new CadastroDAO();
            
            
            cadastros.setNome(campoNome.getText());
            cadastros.setCpf(campoCPF.getText());
            cadastros.setIdade(campoIdade.getText());
            cadastros.setEndereco(campoEndereco.getText());
            cadastros.setTelefone(campoTelefone.getText());
            cadastros.setComorbidade(campoTipo.getText());
            cadastros.setSituacao(campoSituacao.getText());
            
            
            cadastroDAO.save(cadastros);
            
            
            
            int sim = 1;
            
            int nao = 2;
            
            int resposta = 3;
            
            resposta = Integer.parseInt(JOptionPane.showInputDialog("Gostaria de cadastrar outro paciente ou pesquisar?\n 1 = sim\n 2 = nao "));
            
            if (resposta == 1) {  
            
            }else{
            
                dispose();
            
            }
            
            campoNome.setText("");
            campoCPF.setText("");
            campoIdade.setText("");
            campoEndereco.setText("");
            campoTelefone.setText("");
            campoTipo.setText("");
            campoSituacao.setText("");
            
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro_Paciente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            readJTable();
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro_Paciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_campoGravarActionPerformed

    private void campoDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDeletarActionPerformed
        
        campoNome.setText("");
        campoCPF.setText("");
        campoIdade.setText("");
        campoEndereco.setText("");
        campoTelefone.setText("");
        campoTipo.setText("");
        campoSituacao.setText("");
       
            
    }//GEN-LAST:event_campoDeletarActionPerformed

    private void botaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarActionPerformed
       
            String cpf;
   
        try {
            
            Cadastro_Paciente p = new Cadastro_Paciente();
            CadastroDAO C = new CadastroDAO();
            
            
            cpf = JOptionPane.showInputDialog("Qual o cpf?");
            
            
            
             C.getAll(cpf);
             
             
             
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro_Paciente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            readJTable();
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro_Paciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoPesquisarActionPerformed

    private void campoTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelefoneActionPerformed

    private void bntSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSairActionPerformed
    
            dispose();
       
        // TODO add your handling code here:
    }//GEN-LAST:event_bntSairActionPerformed

    private void campodeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campodeletarActionPerformed

        
       int ID;
   
        try {
            
            Cadastro_Paciente p = new Cadastro_Paciente();
            CadastroDAO C = new CadastroDAO();
            
            
            ID = Integer.parseInt(JOptionPane.showInputDialog("Qual o ID?"));
            
            
            
             C.deletar(ID);
             readJTable();
             
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro_Paciente.class.getName()).log(Level.SEVERE, null, ex);
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_campodeletarActionPerformed

    private void campoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAlterarActionPerformed
//
//        int ID;
//
//           
//        try {
//            
//             // TODO add your handling code here:
//            CadastroPaciente cadastros = new CadastroPaciente();
//            
//            CadastroDAO cadastroDAO = new CadastroDAO();
//            
//        
//             ID = Integer.parseInt(JOptionPane.showInputDialog("Qual o ID?"));
//            
//             
//             cadastroDAO.alterar(ID);
//            
//            cadastros.setNome(campoNome.getText());
//            cadastros.setCpf(campoCPF.getText());
//            cadastros.setIdade(campoIdade.getText());
//            cadastros.setEndereco(campoEndereco.getText());
//            cadastros.setTelefone(campoTelefone.getText());
//            cadastros.setComorbidade(campoTipo.getText());
//            cadastros.setSituacao(campoSituacao.getText());
//
//            
//            
//            
//             readJTable();
//            
//            
//            } catch (SQLException ex) {
//            Logger.getLogger(Cadastro_Paciente.class.getName()).log(Level.SEVERE, null, ex);
//        }
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Cadastro_Paciente().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Cadastro_Paciente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSair;
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton campoAlterar;
    private javax.swing.JFormattedTextField campoCPF;
    private javax.swing.JButton campoDeletar;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JButton campoGravar;
    private javax.swing.JTextField campoIdade;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoSituacao;
    private javax.swing.JFormattedTextField campoTelefone;
    private javax.swing.JTextField campoTipo;
    private javax.swing.JButton campodeletar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField7;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.Menu menu5;
    private java.awt.Menu menu6;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.MenuBar menuBar3;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTable tabelaPesquisar;
    // End of variables declaration//GEN-END:variables

   
   

    private void tabelaPesquisar(List<CadastroPaciente> getAll) {
   }

    
}
